_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": val/psnr
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train/loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 12
                - 41
                - 49
                - 50
                - 55
                - 71
                - 105
                - 106
            "2":
                - 1
                - 11
                - 12
                - 41
                - 49
                - 50
                - 55
                - 71
                - 105
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.18.7
            "6": 4.40.0
            "8":
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
lr:
    value: 0.0002
max_epochs:
    value: 150
warmup_epochs:
    value: 15
weight_decay:
    value: 0.0001
